GET http://localhost:3000/tournaments.json

###
GET http://localhost:3000/tournaments/1.json

###
POST http://localhost:3000/tournaments.json
Content-type: Application/json

{
  "name": "Summer Solstice",
  "team_count": 12,
  "location": "Golden, CO",
  "date": "2022-06-21"
}

###
PATCH http://localhost:3000/tournaments/6
Content-type: Application/json

{
  "name": "Summer Solstice",
  "team_count": 12,
  "location": "Golden, CO",
  "date": "2022-06-21"
}

###
DELETE http://localhost:3000/tournaments/6

###
GET http://localhost:3000/teams/1.json

###
POST http://localhost:3000/teams.json
Content-type: Application/json

{
  "name": "Ring of Fire",
  "location": "Raleigh, NC",
  "logo": "https://ringultimate.files.wordpress.com/2017/10/2011clublogo_ringoffire.png"
}

###
PATCH http://localhost:3000/teams/12.json
Content-type: Application/json

{
  "name": "Ring of Fire",
  "location": "Raleigh, NC",
  "logo": "https://ringultimate.files.wordpress.com/2017/10/2011clublogo_ringoffire.png"
}

###
DELETE http://localhost:3000/teams/13